import 'dart:ui';

const supportedPaymentCountries = [
  'Australia',
  'Austria',
  'Belgium',
  'Brazil',
  'Bulgaria',
  'Cameroon',
  'Canada',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  "Cote d'Ivoire",
  'Denmark',
  'Egypt',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Hong Kong',
  'Hungary',
  'India',
  'Indonesia',
  'Ireland',
  'Italy',
  'Japan',
  'Kenya',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malawi',
  'Malaysia',
  'Malta',
  'Mexico',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Rwanda',
  'Senegal',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'Spain',
  'Sweden',
  'Switzerland',
  'Tanzania',
  'Thailand',
  'Uganda',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Zambia',
];

const Map<String, String> _countryCodeToName = {
  'AU': 'Australia',
  'AT': 'Austria',
  'BE': 'Belgium',
  'BR': 'Brazil',
  'BG': 'Bulgaria',
  'CM': 'Cameroon',
  'CA': 'Canada',
  'HR': 'Croatia',
  'CY': 'Cyprus',
  'CZ': 'Czech Republic',
  'CI': "Cote d'Ivoire",
  'DK': 'Denmark',
  'EG': 'Egypt',
  'EE': 'Estonia',
  'FI': 'Finland',
  'FR': 'France',
  'DE': 'Germany',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GR': 'Greece',
  'HK': 'Hong Kong',
  'HU': 'Hungary',
  'IN': 'India',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IT': 'Italy',
  'JP': 'Japan',
  'KE': 'Kenya',
  'LV': 'Latvia',
  'LI': 'Liechtenstein',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'MW': 'Malawi',
  'MY': 'Malaysia',
  'MT': 'Malta',
  'MX': 'Mexico',
  'NL': 'Netherlands',
  'NZ': 'New Zealand',
  'NG': 'Nigeria',
  'NO': 'Norway',
  'PL': 'Poland',
  'PT': 'Portugal',
  'RO': 'Romania',
  'RW': 'Rwanda',
  'SN': 'Senegal',
  'SG': 'Singapore',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'ZA': 'South Africa',
  'ES': 'Spain',
  'SE': 'Sweden',
  'CH': 'Switzerland',
  'TZ': 'Tanzania',
  'TH': 'Thailand',
  'UG': 'Uganda',
  'AE': 'United Arab Emirates',
  'GB': 'United Kingdom',
  'US': 'United States',
  'ZM': 'Zambia',
};

String? supportedCountryFromLocale(Locale locale) {
  final countryCode = locale.countryCode?.toUpperCase();
  if (countryCode == null || countryCode.isEmpty) {
    return null;
  }
  return _countryCodeToName[countryCode];
}

String? supportedCountryNameFromCode(String? countryCode) {
  final normalized = countryCode?.trim().toUpperCase();
  if (normalized == null || normalized.isEmpty) {
    return null;
  }
  return _countryCodeToName[normalized];
}
